# render.yaml
services:
  - type: web
    name: bias-news-api
    env: python
    buildCommand: ""
    startCommand: python backend/app.py
    envVars:
      - key: FLASK_ENV
        value: production
